[build]
  publish = ".next"
  command = "npm run build"
 
[build.environment]
  NODE_VERSION = "20.11.1"

[[redirects]]
  from = "/_next/*"
  to = "/.netlify/next/*"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"